name = "halo-ring-backend"
main = "src/index.js"
compatibility_date = "2024-01-15"

[env.production]
name = "halo-ring-backend"

[env.staging]
name = "halo-ring-backend-staging"

# Environment variables for email service
[vars]
CORS_ORIGIN = "https://your-domain.com"

# KV namespace for storing data
[[kv_namespaces]]
binding = "HALO_DB"
id = "your_kv_namespace_id"
preview_id = "your_preview_kv_namespace_id"

# D1 Database (optional - for more complex data)
# [[d1_databases]]
# binding = "DB"
# database_name = "halo-ring-db"
# database_id = "your_database_id"

# Email service configuration (using Resend or similar)
[secrets]
# Set these using: wrangler secret put EMAIL_API_KEY
# EMAIL_API_KEY = "your_email_service_api_key" 